version: '3'
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    volumes:
     - c:\\ProgramData\\Nudge\\azurite\\:/data
    ports:
     - "10000:10000"
     - "10001:10001"
networks:
  default:
    external:
      name: nudge